events:
  - at: 2025-10-18
    start_at: "19:30"
    end_at: "20:30"
    type: kibele_30
  - at: 2025-11-21
    start_at: "19:30"
    end_at: "20:30"
    type: kibele_dreamform
  - at: 2025-12-14
    start_at: "18:30"
    end_at: "19:30"
    type: kibele_30
    cancelled: true
  - at: 2025-12-14
    start_at: "16:00"
    end_at: "17:00"
    type: kibele_30
  - at: 2025-12-20
    start_at: "18:30"
    end_at: "19:30"
    type: kibele_dreamform
  - at: 2026-01-17
    start_at: "21:00"
    end_at: "22:00"
    type: kibele_dreamform
  - at: 2026-02-20
    start_at: "19:30"
    end_at: "20:30"
    type: kibele_dreamform
  - at: 2026-03-20
    start_at: "21:00"
    end_at: "22:00"
    type: kibele_dreamform

types:
  kibele_dreamform:
    name: Spectacle d’impro « Dreamform »
    calendar_name: Spectacle d’impro des Onironautes
    description: Spectacle d’improvisation théâtrale « Dreamform », inspiré par la vie du public, pour vous emporter dans le monde des rêves.
    location_name: Kibélé
    location_prefix: "Au "
    address: 12 Rue de l’Échiquier, 75010 Paris
    location_url: https://kibele.fr/
    map_url: "https://cartes.app/?allez=Kibele%7Cn3525954557%7C2.3521%7C48.8713"
    entry: Entrée libre, consommation obligatoire, salle au sous-sol, 1h environ.
    image_title: KIBÉLÉ
    image_path: venues/kibele.png

  kibele_30:
    name: Spectacle d’impro « 30 »
    calendar_name: Spectacle d’impro des Onironautes
    description: Spectacle d’improvisation théâtrale « 30 », où trente improvisations devront être jouées, pas une de plus, pas une de moins.
    location_name: Kibélé
    location_prefix: "Au "
    address: 12 Rue de l’Échiquier, 75010 Paris
    location_url: https://kibele.fr/
    map_url: "https://cartes.app/?allez=Kibele%7Cn3525954557%7C2.3521%7C48.8713"
    entry: Entrée libre, consommation obligatoire, salle au sous-sol, 1h environ.
    image_title: KIBÉLÉ
    image_path: venues/kibele.png

  kibele_poulpes:
    name: Rencontre franco-belge avec l’équipe des Poulpes Fiction de Liège
    calendar_name: Rencontre d’impro Poulpes et Onironautes
    description: L’équipe des Pouples Fiction vient tout droit de Liège en Belgique pour rencontrer les Onironautes.
    location_name: Kibélé
    location_prefix: "Au "
    address: 12 Rue de l’Échiquier, 75010 Paris
    location_url: https://kibele.fr/
    map_url: "https://cartes.app/?allez=Kibele%7Cn3525954557%7C2.3521%7C48.8713"
    entry: Entrée libre, consommation obligatoire, salle au sous-sol, 1h environ.
    image_title: KIBÉLÉ
    image_path: venues/kibele.png

  paris_anim_14:
    name: Spectacle d’impro « Dreamform »
    calendar_name: Spectacle d’impro des Onironautes
    description: Spectacle d’improvisation théâtrale « Dreamform », inspiré par la vie du public, pour vous emporter dans le monde des rêves.
    location_name: Centre Paris Anim’ Marc Sangnier
    location_prefix: "Au "
    address: 20/24 avenue Marc Sangnier, 75014 Paris, France
    location_url: https://parisanim14.fr/
    map_url: "https://cartes.app/?allez=Centre%20d'Animation%20Marc-Sangnier%7Cn2478283323%7C2.3097%7C48.8254"
    entry: Entrée libre, 1h environ.
    image_title: Paris Anim
    image_path: venues/paris-anim-14.png
